# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_activity_tct_ui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

from BaseLibrary.common_utils.custom_widgets.custom_widgets import CustomQFrame


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1054, 664)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1041, 631))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(160, 130, 211, 16))
        self.label.setObjectName("label")
        self.btn_match = QtWidgets.QPushButton(self.frame)
        self.btn_match.setGeometry(QtCore.QRect(140, 520, 221, 41))
        self.btn_match.setObjectName("btn_match")
        self.btn_open_file = QtWidgets.QPushButton(self.frame)
        self.btn_open_file.setGeometry(QtCore.QRect(410, 530, 101, 31))
        self.btn_open_file.setObjectName("btn_open_file")
        self.et_save_name = QtWidgets.QLineEdit(self.frame)
        self.et_save_name.setGeometry(QtCore.QRect(340, 120, 281, 31))
        self.et_save_name.setObjectName("et_save_name")
        self.btn_open_logs = QtWidgets.QPushButton(self.frame)
        self.btn_open_logs.setGeometry(QtCore.QRect(550, 530, 101, 31))
        self.btn_open_logs.setObjectName("btn_open_logs")
        self.btn_delete_logs = QtWidgets.QPushButton(self.frame)
        self.btn_delete_logs.setGeometry(QtCore.QRect(700, 540, 101, 21))
        self.btn_delete_logs.setObjectName("btn_delete_logs")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(160, 410, 211, 31))
        self.label_4.setObjectName("label_4")
        self.et_base_col = QtWidgets.QLineEdit(self.frame)
        self.et_base_col.setGeometry(QtCore.QRect(340, 330, 281, 31))
        self.et_base_col.setObjectName("et_base_col")
        self.btn_compare_col = QtWidgets.QPushButton(self.frame)
        self.btn_compare_col.setGeometry(QtCore.QRect(400, 410, 51, 31))
        self.btn_compare_col.setObjectName("btn_compare_col")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(160, 260, 211, 31))
        self.label_6.setObjectName("label_6")
        self.et_sheet_1 = QtWidgets.QLineEdit(self.frame)
        self.et_sheet_1.setGeometry(QtCore.QRect(340, 260, 281, 31))
        self.et_sheet_1.setObjectName("et_sheet_1")
        self.btn_sheet_select_1 = QtWidgets.QPushButton(self.frame)
        self.btn_sheet_select_1.setGeometry(QtCore.QRect(650, 260, 111, 31))
        self.btn_sheet_select_1.setObjectName("btn_sheet_select_1")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(160, 330, 221, 31))
        self.label_5.setObjectName("label_5")
        self.btn_base_col = QtWidgets.QPushButton(self.frame)
        self.btn_base_col.setGeometry(QtCore.QRect(650, 330, 111, 31))
        self.btn_base_col.setObjectName("btn_base_col")
        self.btn_open_compare_list = QtWidgets.QPushButton(self.frame)
        self.btn_open_compare_list.setGeometry(QtCore.QRect(470, 410, 81, 31))
        self.btn_open_compare_list.setObjectName("btn_open_compare_list")
        self.btn_open_switch_check_list = QtWidgets.QPushButton(self.frame)
        self.btn_open_switch_check_list.setGeometry(QtCore.QRect(650, 120, 111, 31))
        self.btn_open_switch_check_list.setObjectName("btn_open_switch_check_list")
        self.lab_trans_threshold = QtWidgets.QLabel(self.frame)
        self.lab_trans_threshold.setGeometry(QtCore.QRect(160, 60, 101, 31))
        self.lab_trans_threshold.setObjectName("lab_trans_threshold")
        self.et_trans_threshold = QtWidgets.QLineEdit(self.frame)
        self.et_trans_threshold.setGeometry(QtCore.QRect(270, 60, 111, 31))
        self.et_trans_threshold.setObjectName("et_trans_threshold")
        self.frame_select_excel = CustomQFrame(self.frame)
        self.frame_select_excel.setGeometry(QtCore.QRect(150, 170, 671, 80))
        self.frame_select_excel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_select_excel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_select_excel.setObjectName("frame_select_excel")
        self.btn_select_dir_1 = QtWidgets.QPushButton(self.frame_select_excel)
        self.btn_select_dir_1.setGeometry(QtCore.QRect(500, 20, 111, 31))
        self.btn_select_dir_1.setObjectName("btn_select_dir_1")
        self.et_dir_path_1 = QtWidgets.QLineEdit(self.frame_select_excel)
        self.et_dir_path_1.setGeometry(QtCore.QRect(190, 20, 281, 31))
        self.et_dir_path_1.setObjectName("et_dir_path_1")
        self.label_2 = QtWidgets.QLabel(self.frame_select_excel)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 211, 41))
        self.label_2.setObjectName("label_2")
        self.frame_select_length_conf = CustomQFrame(self.frame)
        self.frame_select_length_conf.setGeometry(QtCore.QRect(400, 40, 421, 80))
        self.frame_select_length_conf.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_select_length_conf.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_select_length_conf.setObjectName("frame_select_length_conf")
        self.btn_select_length_conf = QtWidgets.QPushButton(self.frame_select_length_conf)
        self.btn_select_length_conf.setGeometry(QtCore.QRect(330, 20, 51, 31))
        self.btn_select_length_conf.setObjectName("btn_select_length_conf")
        self.lab_trans_threshold_2 = QtWidgets.QLabel(self.frame_select_length_conf)
        self.lab_trans_threshold_2.setGeometry(QtCore.QRect(10, 20, 171, 31))
        self.lab_trans_threshold_2.setObjectName("lab_trans_threshold_2")
        self.et_trans_length_conf = QtWidgets.QLineEdit(self.frame_select_length_conf)
        self.et_trans_length_conf.setGeometry(QtCore.QRect(180, 20, 121, 31))
        self.et_trans_length_conf.setObjectName("et_trans_length_conf")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1054, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "报告保存名:"))
        self.btn_match.setText(_translate("MainWindow", "开始检查"))
        self.btn_open_file.setText(_translate("MainWindow", "打开最近报告"))
        self.btn_open_logs.setText(_translate("MainWindow", "打开报告目录"))
        self.btn_delete_logs.setText(_translate("MainWindow", "删除所有报告"))
        self.label_4.setText(_translate("MainWindow", "选择需要进行翻译检查的列(可多选) :"))
        self.btn_compare_col.setText(_translate("MainWindow", "···"))
        self.label_6.setText(_translate("MainWindow", "选择需要检查的\"Sheet\" :"))
        self.btn_sheet_select_1.setText(_translate("MainWindow", "···"))
        self.label_5.setText(_translate("MainWindow", "选择作为翻译基准的列(单选) :"))
        self.btn_base_col.setText(_translate("MainWindow", "···"))
        self.btn_open_compare_list.setText(_translate("MainWindow", "查看已选"))
        self.btn_open_switch_check_list.setText(_translate("MainWindow", "选择需要检查项"))
        self.lab_trans_threshold.setText(_translate("MainWindow", "译文长度阈值(%):"))
        self.btn_select_dir_1.setText(_translate("MainWindow", "···"))
        self.label_2.setText(_translate("MainWindow", "选择需要进行检查的Excel文件 :\n"
"(可将文件直接拖到这个区域)"))
        self.btn_select_length_conf.setText(_translate("MainWindow", "···"))
        self.lab_trans_threshold_2.setText(_translate("MainWindow", "长度检查配置:\n"
"(可将文件直接拖到这个区域)"))
        self.menu.setTitle(_translate("MainWindow", "选项"))

